import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get('window');

export const global = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#1A1A1A',
    },
    keyboardAvoidingView: {
        flex: 1,
    },
    container: {
        marginTop: height * 0.1,
        paddingHorizontal: width * 0.06,
        paddingVertical: height * 0.08,
    },
    header: {
        alignItems: 'center',
        marginBottom: height * 0.05,
    },
    titulo: {
        fontSize: 32,
        fontWeight: '300',
        color: '#DC143C',
        letterSpacing: 1.2,
        textAlign: 'center',
    },
    subtitulo: {
        fontSize: 16,
        color: '#B8B8B8',
        marginTop: height * 0.02,
        textAlign: 'center',
        lineHeight: 24,
        letterSpacing: 0.3,
    },  
    content: {
        borderRadius: 20,
        padding: width * 0.05,
        shadowColor: '#000000',
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 20,
        elevation: 15,
        backgroundColor: '#2D2D2D',
        borderWidth: 1,
        borderColor: '#444444',
    },
    inputGroup: {
       marginBottom: height * 0.03,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#DC143C',
        marginBottom: height * 0.012,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    inputIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: width * 0.04,
        borderWidth: 1.5,
        borderColor: '#555555',
        borderRadius: 14,
        backgroundColor: '#3A3A3A',
        height: height * 0.065,
        shadowColor: '#000000',
        shadowOpacity: 0.2,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    inputError: {
        backgroundColor: '#3A2A2A',
        borderColor: '#FF6B6B',
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#E8E8E8',
        fontWeight: '500',
        marginLeft: width * 0.03,
        paddingHorizontal: width * 0.03,
        letterSpacing: 0.2,
    },
    eyeIcon: {
        position: 'absolute',
        right: 12,
        top: 42
    },
    errorText: {
        color: '#FF6B6B',
        fontSize: 13,
        fontWeight: '500',
        marginTop: height * 0.008,
        marginLeft: width * 0.02,
        fontStyle: 'italic',
    },
    primaryButton: {
        backgroundColor: '#DC143C',
        borderRadius: 16,
        padding: width * 0.04,
        justifyContent: 'center',
        alignItems: 'center',
        height: height * 0.065,
        marginTop: height * 0.03,
        shadowColor: '#B22222',
        shadowOpacity: 0.5,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: '#B22222',
    },
    primaryButtonDisabled: {
        backgroundColor: '#555555',
        borderRadius: 16,
        padding: width * 0.04,
        justifyContent: 'center',
        alignItems: 'center',
        height: height * 0.065,
        marginTop: height * 0.03,
        borderWidth: 1,
        borderColor: '#666666',
    },
    primaryButtonText: {
        color: '#FFFFFF',
        fontSize: 17,
        fontWeight: '600',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    buttonTextDisabled: {
        color: '#999999',
        fontSize: 17,
        fontWeight: '600',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    // BOTÕES ADICIONAIS
    secondaryButton: {
        backgroundColor: 'transparent',
        borderRadius: 16,
        padding: width * 0.04,
        justifyContent: 'center',
        alignItems: 'center',
        height: height * 0.065,
        marginTop: height * 0.02,
        borderWidth: 2,
        borderColor: '#DC143C',
    },
    secondaryButtonText: {
        color: '#DC143C',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 1.2,
    },
    tertiaryButton: {
        backgroundColor: 'transparent',
        borderRadius: 16,
        padding: width * 0.04,
        justifyContent: 'center',
        alignItems: 'center',
        height: height * 0.055,
        marginTop: height * 0.015,
        borderWidth: 1,
        borderColor: '#777777',
    },
    tertiaryButtonText: {
        color: '#B8B8B8',
        fontSize: 14,
        fontWeight: '500',
        letterSpacing: 0.8,
    },
    linkButton: {
        backgroundColor: 'transparent',
        padding: width * 0.02,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: height * 0.01,
    },
    linkButtonText: {
        color: '#DC143C',
        fontSize: 14,
        fontWeight: '500',
        textDecorationLine: 'underline',
        letterSpacing: 0.5,
    },
});