import { Dimensions, StyleSheet } from "react-native";

const { width, height } = Dimensions.get('window');

export const global = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#fdf8fa',
    },
    keyboardAvoidingView: {
        flex: 1,
    },
    container: {
        marginTop: height * 0.1,
        paddingHorizontal: width * 0.06,
        paddingVertical: height * 0.05,
    },
    header: {
        alignItems: 'center',
        marginBottom: height * 0.05,
    },
    titulo: {
        fontSize: 32,
        fontWeight: '300',
        color: '#5a0d2a',
        letterSpacing: 1.2,
        textAlign: 'center',
    },
    subtitulo: {
        fontSize: 16,
        color: '#8c6d7e',
        marginTop: height * 0.02,
        textAlign: 'center',
        lineHeight: 24,
        letterSpacing: 0.3,
    },  
    content: {
        borderRadius: 20,
        padding: width * 0.05,
        shadowColor: '#5a0d2a',
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 8 },
        shadowRadius: 20,
        elevation: 15,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#f5e8ed',
    },
    inputGroup: {
       marginBottom: height * 0.03,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#5a0d2a',
        marginBottom: height * 0.012,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    inputIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingLeft: width * 0.04,
        borderWidth: 1.5,
        borderColor: '#e8d8df',
        borderRadius: 14,
        backgroundColor: '#fefbfd',
        height: height * 0.065,
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    inputError: {
        backgroundColor: '#fdf2f2',
        borderColor: '#b91c1c',
    },
    input: {
        flex: 1,
        fontSize: 16,
        color: '#2d1a23',
        fontWeight: '500',
        marginLeft: width * 0.03,
        paddingHorizontal: width * 0.03,
        letterSpacing: 0.2,
    },
    eyeIcon: {
        position: 'absolute',
        right: 12,
        top: 42
    },
    errorText: {
        color: '#b91c1c',
        fontSize: 13,
        fontWeight: '500',
        marginTop: height * 0.008,
        marginLeft: width * 0.02,
        fontStyle: 'italic',
    },
    primaryButton: {
        backgroundColor: '#5a0d2a',
        borderRadius: 16,
        padding: width * 0.04,
        justifyContent: 'center',
        alignItems: 'center',
        height: height * 0.065,
        marginTop: height * 0.03,
        shadowColor: '#5a0d2a',
        shadowOpacity: 0.4,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: '#4a0a22',
    },
    primaryButtonDisabled: {
        backgroundColor: '#a8a8a8',
        borderRadius: 16,
        padding: width * 0.04,
        justifyContent: 'center',
        alignItems: 'center',
        height: height * 0.065,
        marginTop: height * 0.03,
        borderWidth: 1,
        borderColor: '#989898',
    },
    primaryButtonText: {
        color: '#ffffff',
        fontSize: 17,
        fontWeight: '600',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
    buttonTextDisabled: {
        color: '#e0e0e0',
        fontSize: 17,
        fontWeight: '600',
        letterSpacing: 1.5,
        textTransform: 'uppercase',
    },
});